import { Shell } from "@/components/Shell";
import { prisma } from "@/lib/db";
import { fmtDate, fmtRelative } from "@/lib/format";
import { eventTypeMeta, type LockinEventType } from "@/lib/lockin-rules";
import { MarkAllReadButton } from "@/components/MarkAllReadButton";

export const dynamic = "force-dynamic";

export default async function NotificationsPage() {
  const notifications = await prisma.notification.findMany({
    orderBy: { createdAt: "desc" },
    take: 100,
  });
  const unread = notifications.filter((n) => !n.readAt).length;

  return (
    <Shell active="/notifications">
      <div className="mb-3 flex items-center gap-3">
        <h1 className="text-sm font-semibold">Alerts</h1>
        {unread > 0 && (
          <span className="rounded-full bg-accent px-1.5 py-0.5 text-[10px] font-semibold text-accent-fg">
            {unread} unread
          </span>
        )}
        <div className="ml-auto">{unread > 0 && <MarkAllReadButton />}</div>
      </div>

      {notifications.length === 0 ? (
        <p className="rounded-lg border border-border bg-surface px-4 py-8 text-center text-sm text-fg-muted">
          No alerts yet. They are generated by the daily job at T-7, T-1 and on the morning
          of each unlock, per the rules in Settings.
        </p>
      ) : (
        <ul className="space-y-1.5">
          {notifications.map((n) => (
            <li
              key={n.id}
              className={`rounded-lg border px-3 py-2 text-sm ${
                n.readAt ? "border-border bg-surface/50 opacity-60" : "border-border-strong bg-surface"
              }`}
            >
              <div className="flex flex-wrap items-center gap-x-2 gap-y-1">
                {!n.readAt && <span className="h-1.5 w-1.5 rounded-full bg-accent" />}
                <span className="text-[11px] text-fg-dim">
                  {eventTypeMeta[n.eventType as LockinEventType].short}
                </span>
                <span>{n.message}</span>
                <span className="ml-auto text-xs text-fg-dim tnum">
                  unlock {fmtDate(n.scheduledFor.toISOString().slice(0, 10))} ·{" "}
                  {fmtRelative(n.createdAt.toISOString())}
                </span>
              </div>
            </li>
          ))}
        </ul>
      )}
    </Shell>
  );
}
